# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63298c311420e067109825705b5c9e17ffef2f98d26f8fb94fb36218cc5b37d70d421f6235f3e9f9084aa09568ac0bbb7fa03f894fbd443b533fa2d9112e9247

test:
  secret_key_base: d9c2498bc1ddbe38980b3ce168318e5969e33a4b882709ba06e2956590419a619a75ffbd4e5db43a0fa7710bf3f5c97feafb6859a755d539d223ed0da56eb941

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
